import { PrismaClient, PaymentChannelType } from '@prisma/client';

const prisma = new PrismaClient();

const paymentMethods = [
  // Virtual Accounts
  {
    code: 'PERMATAVA',
    name: 'Permata Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/szezRhAALB1583408731.png',
    isActive: true,
    sortOrder: 1,
  },
  {
    code: 'BNIVA',
    name: 'BNI Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/n22Qsh8jMa1583433577.png',
    isActive: true,
    sortOrder: 2,
  },
  {
    code: 'BRIVA',
    name: 'BRI Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/8WQ3APST5s1579461828.png',
    isActive: true,
    sortOrder: 3,
  },
  {
    code: 'MANDIRIVA',
    name: 'Mandiri Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/T9Z012UE331583531536.png',
    isActive: true,
    sortOrder: 4,
  },
  {
    code: 'BCAVA',
    name: 'BCA Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 5500,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/ytBKvaleGy1605201833.png',
    isActive: true,
    sortOrder: 5,
  },
  {
    code: 'MUAMALATVA',
    name: 'Muamalat Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/GGwwcgdYaG1611929720.png',
    isActive: true,
    sortOrder: 6,
  },
  {
    code: 'CIMBVA',
    name: 'CIMB Niaga Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/WtEJwfuphn1614003973.png',
    isActive: true,
    sortOrder: 7,
  },
  {
    code: 'BSIVA',
    name: 'BSI Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/tEclz5Assb1643375216.png',
    isActive: true,
    sortOrder: 8,
  },
  {
    code: 'OCBCVA',
    name: 'OCBC NISP Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/ysiSToLvKl1644244798.png',
    isActive: true,
    sortOrder: 9,
  },
  {
    code: 'DANAMONVA',
    name: 'Danamon Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/F3pGzDOLUz1644245546.png',
    isActive: true,
    sortOrder: 10,
  },
  {
    code: 'OTHERBANKVA',
    name: 'Other Bank Virtual Account',
    group: 'Virtual Account',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 4250,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/qQYo61sIDa1702995837.png',
    isActive: true,
    sortOrder: 11,
  },
  // Convenience Stores
  {
    code: 'ALFAMART',
    name: 'Alfamart',
    group: 'Convenience Store',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 3500,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 2500000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/jiGZMKp2RD1583433506.png',
    isActive: true,
    sortOrder: 12,
  },
  {
    code: 'INDOMARET',
    name: 'Indomaret',
    group: 'Convenience Store',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 3500,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 10000,
    maximumAmount: 2500000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/zNzuO5AuLw1583513974.png',
    isActive: true,
    sortOrder: 13,
  },
  {
    code: 'ALFAMIDI',
    name: 'Alfamidi',
    group: 'Convenience Store',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 3500,
    feeMerchantPercent: 0,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 5000,
    maximumAmount: 2500000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/aQTdaUC2GO1593660384.png',
    isActive: true,
    sortOrder: 14,
  },
  // E-Wallets
  {
    code: 'OVO',
    name: 'OVO',
    group: 'E-Wallet',
    type: PaymentChannelType.REDIRECT,
    feeMerchantFlat: 0,
    feeMerchantPercent: 3,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumFee: 1000,
    minimumAmount: 1000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/fH6Y7wDT171586199243.png',
    isActive: true,
    sortOrder: 15,
  },
  {
    code: 'QRIS',
    name: 'QRIS by ShopeePay',
    group: 'E-Wallet',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 750,
    feeMerchantPercent: 0.7,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 1000,
    maximumAmount: 5000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/BpE4BPVyIw1605597490.png',
    isActive: true,
    sortOrder: 16,
  },
  {
    code: 'QRISC',
    name: 'QRIS (Customizable)',
    group: 'E-Wallet',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 750,
    feeMerchantPercent: 0.7,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 1000,
    maximumAmount: 5000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/m9FtFwaBCg1623157494.png',
    isActive: true,
    sortOrder: 17,
  },
  {
    code: 'QRIS2',
    name: 'QRIS',
    group: 'E-Wallet',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 750,
    feeMerchantPercent: 0.7,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 1000,
    maximumAmount: 5000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/8ewGzP6SWe1649667701.png',
    isActive: true,
    sortOrder: 18,
  },
  {
    code: 'DANA',
    name: 'DANA',
    group: 'E-Wallet',
    type: PaymentChannelType.REDIRECT,
    feeMerchantFlat: 0,
    feeMerchantPercent: 3,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumFee: 1000,
    minimumAmount: 1000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/sj3UHLu8Tu1655719621.png',
    isActive: true,
    sortOrder: 19,
  },
  {
    code: 'SHOPEEPAY',
    name: 'ShopeePay',
    group: 'E-Wallet',
    type: PaymentChannelType.REDIRECT,
    feeMerchantFlat: 0,
    feeMerchantPercent: 3,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumFee: 1000,
    minimumAmount: 1000,
    maximumAmount: 10000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/d204uajhlS1655719774.png',
    isActive: true,
    sortOrder: 20,
  },
  {
    code: 'QRIS_SHOPEEPAY',
    name: 'QRIS Custom by ShopeePay',
    group: 'E-Wallet',
    type: PaymentChannelType.DIRECT,
    feeMerchantFlat: 750,
    feeMerchantPercent: 0.7,
    feeCustomerFlat: 0,
    feeCustomerPercent: 0,
    minimumAmount: 1000,
    maximumAmount: 5000000,
    iconUrl: 'https://assets.tripay.co.id/upload/payment-icon/DM8sBd1i9y1681718593.png',
    isActive: true,
    sortOrder: 21,
  },
];

export async function seedPaymentMethods() {
  console.log('🌱 Seeding payment methods...');
  for (const method of paymentMethods) {
    // upsert memastikan idempotency saat dijalankan berkali-kali
    await prisma.paymentMethod.upsert({
      where: { code: method.code },
      update: method,
      create: method,
    });
  }
  console.log('✅ Payment methods seeded successfully!');
}

export async function clearPaymentMethods() {
  await prisma.paymentMethod.deleteMany();
  console.log('🗑️  Payment methods cleared!');
}

// wrapper main supaya file berjalan saat dipanggil langsung
async function main() {
  try {
    await prisma.$connect();
    // pilih salah satu: seed atau clear
    // await clearPaymentMethods(); // uncomment kalau mau hapus semua dulu
    await seedPaymentMethods();
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

// Jika file dieksekusi langsung (node / ts-node), jalankan main
if (require.main === module) {
  main();
}
